### ISSUE TITLE
NameError in Dradis::Plugins::HtmlExport::BaseController#index 

### ISSUE THREAD

**Issue by ChriZzn** [dradis/dradis-html_export#3]
I get this error when I open the "basic.html.erb" report.

undefined local variable or method `reporting_cat' for #<Dradis::Plugins::HtmlExport::Exporter:0x87761efc>

Rails.root: /usr/lib/dradis

I'm using the default installation in Kali Linux

**Comment by rachkor** [comment]
Hi @ChriZzn let's narrow down whether this is a problem with the template or with the exporter. First, what version of Dradis are you running? The footer of the left-hand sidebar is the best place to check for this info. 
Second, are you getting this error with other HTML templates or just the `basic.html.erb` file? To check another template, I'd recommend downloading one of the compliance packs like the OSCP pack here: https://dradisframework.com/academy/industry/compliance/

**Comment by etdsoft** [comment]
This is a problem with the code and will be fixed by https://github.com/dradis/dradis-html_export/pull/4 watch this space!

**Comment by etdsoft** [comment]
PR#4 was merged, this should be fixed. Reopen in dradis/dradis-ce/issues if not.
